### ISSUE TITLE
Subsample to a fixed number of reads

### ISSUE THREAD

**Issue by Midnighter** [stjude-rust-labs/fq#22]
Hi,

I'm wondering what you think about adding an option to subsample a FastQ file to a specific number of reads? This comes in handy when subsampling many FastQ files to a lowest common number of reads, for example. `seqtk` offers this option.

The reason I'm asking here is that memory consumption of `seqtk` can be quite high and I was wondering if you know that `fq` has a smaller footprint.

Thank you for your input.

**Comment by zaeleus** [comment]
Hi, @Midnighter!

I wouldn't expect seqtk to use an exceptionally large amount of memory when using the two-pass option (`-2`), if you're not already doing so.

Otherwise, `fq subsample` now takes either a `-p/--probability <f32>` option for a proportional, approximate number of records or `-n/--record-count <u64>` for an exact number of records. These options are mutually exclusive and use different strategies.

As a quick test for exact subsampling, here are run times and max memory usages (median of 3 runs) for seqtk 1.3-r117-dirty (lh3/seqtk@7c04ce7898ad5909bd309c6ba3cd9c3bd0651f0e) and fq v0.9.0 (4636ccf5c 2022-02-10). The input is 150 million synthetic records (47.7 GiB)[^1], and the output is being subsampled to 30 million (20%) records.

| command                                                     | wall time (s) | max memory usage (MiB) |
|-------------------------------------------------------------|--------------:|-----------------------:|
| `sektq sample 150m.fq 30000000 > /dev/null`                 |          77.1 |                  21100 |
| `sektq sample -2 150m.fq 30000000 > /dev/null`              |          98.5 |                    766 |
| `fq subsample -s 11 -n 30000000 --r1-dst /dev/null 150m.fq` |          44.9 |                   19.3 |

[^1]: `fq generate --record-count 150000000 --read-length 151 150m.fq /dev/null`

**Comment by Midnighter** [comment]
What a marvelous answer. Thank you very much. I must admit that I missed `seqtk`'s two-pass option so that's an obvious thing to try for me. However, it looks like `fq` might be even better performing still.

**Comment by Midnighter** [comment]
As a follow up, what do you think about having a bioconda recipe for `fq`? I would be happy to add one. This would ensure not only a conda package but automatically built Docker and Singularity images. Pretty much the standard option for https://nf-co.re/ pipelines.

**Comment by Midnighter** [comment]
It's common practice to add tool authors as maintainers. I can open a PR to add a recipe and ping you there.

**Comment by zaeleus** [comment]
I'll note that I myself am not a Bioconda user, but I have no problem with a community-led recipe being created. @Midnighter, if you'd like to volunteer, go ahead.

**Comment by Midnighter** [comment]
For posterity, this is now deployed at https://anaconda.org/bioconda/fq

**Comment by zaeleus** [comment]
Nice! Thanks, @Midnighter!
